"""
primitives/pkg_name_remap.py — PRIM-005: package_name_remap

Replaces a Debian-specific package name in a shell script with the distro-specific
equivalent determined by the normalization table.

Example:
  Before: apt-get install -y libssl-dev
  After:  apt-get install -y libssl-dev   (Ubuntu stays the same)
  — but in the dispatch block generated by PRIM-001:
  fedora uses: openssl-devel
  arch uses:   openssl

This primitive is most useful for standalone package name references
(e.g. in comments, documentation, or scripts that have already been
partially adapted by PRIM-001 but contain other Debian-specific names).
"""
from __future__ import annotations

import re

from black_flag.adapters.normalization import NORMALIZATION_TABLE, resolve_package
from .base import AdaptationPrimitive, PrimitiveNotApplicable

# All known Debian-specific package names (values from the normalization table)
_DEBIAN_NAMES: dict[str, str] = {}
for _generic, _distro_map in NORMALIZATION_TABLE.items():
    _debian_name = _distro_map.get("ubuntu") or _distro_map.get("debian")
    if _debian_name:
        _DEBIAN_NAMES[_debian_name] = _generic  # debian_name → generic_name


class PackageNameRemapPrimitive(AdaptationPrimitive):
    id = "package_name_remap"
    description = "Replace Debian-specific package names with distro-aware equivalents"
    supported_file_types = [".sh", ".bash", ".py", ".txt"]
    safe_to_auto_apply = True

    def matches(self, file_content: str, file_ext: str) -> bool:
        if file_ext not in self.supported_file_types:
            return False
        return any(name in file_content for name in _DEBIAN_NAMES)

    def apply(self, file_content: str, params: dict, adapters: dict) -> str:
        debian_name = params.get("debian_name", "")

        if not debian_name:
            # Auto-mode: find the first Debian package name in the content
            for name in _DEBIAN_NAMES:
                if name in file_content:
                    debian_name = name
                    break
            if not debian_name:
                raise PrimitiveNotApplicable(
                    "package_name_remap: no known Debian package names found in content"
                )

        generic_name = _DEBIAN_NAMES.get(debian_name)
        if generic_name is None:
            raise PrimitiveNotApplicable(
                f"package_name_remap: '{debian_name}' is not in the normalization table"
            )

        if debian_name not in file_content:
            raise PrimitiveNotApplicable(
                f"package_name_remap: '{debian_name}' not found in file content"
            )

        # Add an inline comment noting the remapping (does not break shell or Python syntax)
        result = file_content.replace(
            debian_name,
            f"{debian_name}  # bf:package-remap generic={generic_name}",
            1,
        )
        return result
